version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=user-story-api
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: